/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppProvider: typeof import('./../components/common/app-provider.vue')['default']
    GlobalContent: typeof import('./../components/layout/modules/global-content/index.vue')['default']
    GlobalFooter: typeof import('./../components/layout/modules/global-footer/index.vue')['default']
    GlobalLogo: typeof import('./../components/layout/modules/global-logo/index.vue')['default']
    GlobalTabbar: typeof import('./../components/layout/modules/global-tabbar/index.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    Layout: typeof import('./../components/layout/index.vue')['default']
    LoadingButton: typeof import('./../components/common/loading-button.vue')['default']
    NavLeft: typeof import('./../components/layout/modules/nav-left/index.vue')['default']
    NavRight: typeof import('./../components/layout/modules/nav-right/index.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NFlex: typeof import('naive-ui')['NFlex']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
