/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppProvider: typeof import('./../components/common/app-provider.vue')['default']
    Breadcrumbs: typeof import('./../components/layout/modules/nav-left/modules/breadcrumbs.vue')['default']
    ButtonIcon: typeof import('./../components/custom/button-icon.vue')['default']
    FullScreen: typeof import('./../components/common/full-screen.vue')['default']
    GlobalContent: typeof import('./../components/layout/modules/global-content/index.vue')['default']
    GlobalFooter: typeof import('./../components/layout/modules/global-footer/index.vue')['default']
    GlobalHeader: typeof import('./../components/layout/modules/global-header/index.vue')['default']
    GlobalLogo: typeof import('./../components/layout/modules/global-logo/index.vue')['default']
    GlobalSearch: typeof import('./../components/layout/modules/global-search/index.vue')['default']
    GlobalTabbar: typeof import('./../components/layout/modules/global-tabbar/index.vue')['default']
    HeaderLeft: typeof import('../components/layout/modules/nav-left/index.vue')['default']
    HeaderRight: typeof import('./../components/layout/modules/global-header/modules/header-right.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    IconGridiconsFullscreen: typeof import('~icons/gridicons/fullscreen')['default']
    IconGridiconsFullscreenExit: typeof import('~icons/gridicons/fullscreen-exit')['default']
    IconUilSearch: typeof import('~icons/uil/search')['default']
    Layout: typeof import('./../components/layout/index.vue')['default']
    LoadingButton: typeof import('./../components/common/loading-button.vue')['default']
    NavLeft: typeof import('./../components/layout/modules/nav-left/index.vue')['default']
    NavRight: typeof import('./../components/layout/modules/nav-right/index.vue')['default']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NFlex: typeof import('naive-ui')['NFlex']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NTooltip: typeof import('naive-ui')['NTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchModal: typeof import('./../components/layout/modules/global-search/components/search-modal.vue')['default']
    SvgIcon: typeof import('./../components/custom/svg-icon.vue')['default']
    ThemeButton: typeof import('./../components/layout/modules/nav-right/components/theme-button.vue')['default']
    ThemeSchemaSwitch: typeof import('./../components/common/theme-schema-switch.vue')['default']
    UserAvatar: typeof import('./../components/layout/modules/nav-right/components/user-avatar.vue')['default']
  }
}
